client_header_buffer_size 64k;
large_client_header_buffers 4 64k;
client_max_body_size 100M;

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://api:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }

    location /wilayah-logo {
        proxy_pass http://minio:9000/wilayah-logo;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Cookie "";
        proxy_hide_header Set-Cookie;
        proxy_ignore_headers Set-Cookie;

        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }
}
